//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceYourLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonoContrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BonoContrato()
        {
            this.FlujoPeriodico = new HashSet<FlujoPeriodico>();
        }
    
        public int IDBonoContrato { get; set; }
        public decimal ValorComercial { get; set; }
        public decimal ValorNominal { get; set; }
        public int NroAños { get; set; }
        public string FrecuenciaPago { get; set; }
        public int DiasPorAño { get; set; }
        public string TipoTasaInteres { get; set; }
        public string Capitalizacion { get; set; }
        public double TasaInteresAnual { get; set; }
        public double TasaDescuentoAnual { get; set; }
        public double ImpuestoRenta { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public int FK_IDBonista { get; set; }
        public int FK_IDCostesIniciales { get; set; }
        public int FK_IDEmpresaEmisora { get; set; }
    
        public virtual CostesIniciales CostesIniciales { get; set; }
        public virtual EmpresaEmisora EmpresaEmisora { get; set; }
        public virtual UsuarioBonista UsuarioBonista { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlujoPeriodico> FlujoPeriodico { get; set; }
    }
}
