//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceYourLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostesIniciales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CostesIniciales()
        {
            this.BonoContrato = new HashSet<BonoContrato>();
        }
    
        public int IDCostesIniciales { get; set; }
        public double PorcPrima { get; set; }
        public Nullable<double> PorcEstructuracion { get; set; }
        public Nullable<double> PorcColocacion { get; set; }
        public Nullable<double> PorcFlotacion { get; set; }
        public Nullable<double> PorcCAVALI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BonoContrato> BonoContrato { get; set; }
    }
}
