//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceYourLife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlujoPeriodico
    {
        public int IDFlujoPeriodico { get; set; }
        public decimal Bono { get; set; }
        public decimal BonoIndexado { get; set; }
        public decimal Cupon { get; set; }
        public decimal Cuota { get; set; }
        public decimal Amortizacion { get; set; }
        public decimal Prima { get; set; }
        public decimal Escudo { get; set; }
        public decimal FlujoEmisor { get; set; }
        public decimal FlujoEmisorEscudo { get; set; }
        public decimal FlujoBonista { get; set; }
        public decimal ValorBonoDCP { get; set; }
        public int FK_IDBonoContrato { get; set; }
    
        public virtual BonoContrato BonoContrato { get; set; }
    }
}
