//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceYourLife.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinanceYourLifeEntities1 : DbContext
    {
        public FinanceYourLifeEntities1()
            : base("name=FinanceYourLifeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgenteExterno> AgenteExterno { get; set; }
        public virtual DbSet<BonoContrato> BonoContrato { get; set; }
        public virtual DbSet<CostesIniciales> CostesIniciales { get; set; }
        public virtual DbSet<EmpresaEmisora> EmpresaEmisora { get; set; }
        public virtual DbSet<FlujoPeriodico> FlujoPeriodico { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<UsuarioBonista> UsuarioBonista { get; set; }
    }
}
