//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceYourLife.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class UsuarioBonista
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsuarioBonista()
        {
            this.BonoContrato = new HashSet<BonoContrato>();
        }
    
        public int IDUsuarioBonista { get; set; } 

        [Required(ErrorMessage ="firstName is required.")]
        public string Nombres { get; set; } 

        [Required(ErrorMessage = "LastName is required.")]
        public string Apellidos { get; set; } 

        [Required(ErrorMessage = "Email is required.")]
        public string Correo { get; set; }

        [Required(ErrorMessage = "Password is required.")]
        [DataType(DataType.Password)] 
        [DisplayName("Password")]
        public string Contraseña { get; set; } 

        [DataType(DataType.Password)]
        [DisplayName("Confirm Password")] 
        [Compare("Contraseña")]
        public string ConfirmarContraseña { get; set; }

        [Required(ErrorMessage = "RUC Number is required.")]
        public string RUC { get; set; } 
        
        [DisplayName("Customer")]
        public int IDTipoUsuario { get; set; }
        //"IDUsuarioBonista,Nombres,Apellidos,Correo,Contraseña,RUC,ConfirmarContraseña"

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BonoContrato> BonoContrato { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
